### ISSUE TITLE
Discussion style plotting arguments

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/Spectra#113]
Currently our `plotSpectra*` functions have the `label*` arguments (`labelPos`, `labelAdj`, ...)

Even in base `R` there are at least two paradigms for solving the problem of equally named arguments for multiple functions:
`legend`: `box.col`, `title.col`, `text.col` (similar to our current approach)
`dendrogram`: `edgePar` (a named `list`, e.g. `edgePar = list(col = "red", ...)`)

Do we want to keep our current approach:
```r
plotSpectra <- function(...
                        labelCex = 1, labelSrt = 0,
                        labelAdj = NULL, labelPos = NULL,
                        labelOffset = 0.5, ...) {
```
Or switch to something like
```r
plotSpectra <- function(..., labels.arg = c(cex = 1, srt = 0, offset = 0.5), ...) {
```

I would prefer the named `list` approach.

**Comment by jorainer** [comment]
Thanks @sgibb for the input - and I prefer the current approach :) - which means we have to wait for @lgatto to vote on this.
 
I in general don't like `list` parameters because IMHO they are less user friendly and more difficult to define/pass and check. Also, directly naming the parameters makes them more explicit (and it's easier to document.

**Comment by jorainer** [comment]
@lgatto , could you please also have a look at this issue? I think we should settle this also before submission.

**Comment by sgibb** [comment]
Submission is done. So we keep it that way.
