### ISSUE TITLE
dataStorage and dataOrigin semantics

### ISSUE THREAD

**Issue by meowcat** [rformassspectrometry/Spectra#179]
Hi,

question: is there any specific guidance of how `dataStorage` and `dataOrigin` should work? Or is this up to the backend?

For example, if I have a text format backend and I want to specify how to split the output into different files on export, would it be an acceptable use to set one of these fields correspondingly? Or should I add an additional variable like "exportTarget" for that?

**Comment by jorainer** [comment]
The `dataStorage` is defined in the backend and you should not change that (for on-disk backends this keeps the information where the data is stored). 

The `dataOrigin` should allow to keep track where the data comes from (e.g. the originating mzML file). There is no constraint on this variable, so it can be changed by the user.

For your use case I would suggest to add a new variable instead of using one of these.

**Comment by meowcat** [comment]
Thanks for the clarification!
