### ISSUE TITLE
Default serial backend on `containsMz` and `containsNeutralLoss` make them unusable on Windows

### ISSUE THREAD

**Issue by Adafede** [rformassspectrometry/Spectra#340]
Hi,

I was recently using both `containsMz` and `containsNeutralLoss` in the frame of https://github.com/spectra-to-knowledge/SpectraToQueries and when testing them on Windows I realized that the switch to serial makes them run for hours instead of seconds ... (see https://github.com/spectra-to-knowledge/SpectraToQueries/actions/runs/11898195032)
I looked at the [methods](https://github.com/rformassspectrometry/Spectra/blob/bfffb9120e73308c3077bb1144a16e9198fc1043/R/Spectra.R#L3274-L3321) and saw multiple comments regarding possible implementation improvements...is this work in progress? 

Any starting point to eventually help?

**Comment by jorainer** [comment]
hm, it is weird that this should happen only on Windows... I don't quite understand that. But yes, there would/could be room for improvement for these methods. Some thoughts:

- `.peaksapply` would return a `list` of matrices - for a `MsBackendMemory` that would be faster than calling `mz()` because of the way the data is represented internally. Honestly, I don't remember why I added that comment...
- depending on the data set and the memory available, loading  **all** m/z values into memory and processing them can slow things down. That's why we're using chunk-wise processing for most other methods at the moment. Then we're only loading and processing the m/z values for one *chunk* of spectra at a time. Before digging into details there I would maybe try to see if using `chunkapply()` on your `Spectra` would help (i.e. splitting the `Spectra` into chunks and processing each separately to reduce memory demand).

And of course, any contribution highly welcome!

**Comment by Adafede** [comment]
Thank you for your super fast answer!

Did I get it wrong or what you suggest should be the default behaviour? (at least what I understood from this in the doc?)

```
applyProcessing(
  object,
  f = processingChunkFactor(object),
  BPPARAM = bpparam(),
  ...
)
```

I probably do not fully understand the magics behind the backends and how explicit one should be to be sure to get the right one.

Maybe worth mentioning I am not using the official `containsNeutralLoss` as I needed the `which=all` argument present in the `containsMz` method.
(see https://github.com/spectra-to-knowledge/SpectraToQueries/blob/main/R/perform_query.R)
I don't think this has a huge impact but still...

**Comment by jorainer** [comment]
It would be rather

```r
chunkapply(object, chunkSize = 1000, FUN = ... )
```

that would simply split your `object` into smaller `Spectra` with 1000 spectra each and call the function `FUN` in each. Thus, only m/z values of the 1000 spectra are loaded at a time instead of, as by default, all m/z values in one go.

Just to understand your function `perform_query` - is `spectra` a large `Spectra` (i.e. with many spectra in it) or only a `Spectra` with one spectrum?

**Comment by jorainer** [comment]
If OK for you I would have a look into the `containsMz()` function to see what I actually wanted to implement there. I believe it was the chunk-wise processing... but I don't recall now... maybe I should have used a more descriptive comment :)

**Comment by Adafede** [comment]
It is a _relatively_ small `Spectra` object containing 300 spectra. And I want to filter the ones matching my query...a bit something `SpectraQL` like

**Comment by Adafede** [comment]
@jorainer Your guidance helped me fixing the issue, which was not what I expected...in the end I had to do the exact opposite of what the title says...**explicitly turn to serial backend** 😆

**Comment by jorainer** [comment]
OK, so, in the end the issue was nested parallel processing, i.e. your function as well as the `Spectra` functions using their own parallel processing?

**Comment by Adafede** [comment]
Exactly, which somehow seems handled better on *nix systems which saved me until now

**Comment by jorainer** [comment]
OK, thanks for the update. Good to know and be aware of this - to avoid in future :)

I'm closing the issue now - feel free to reopen if needed.
