### ISSUE TITLE
MsBackend interface

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#4]
See also #2 

# MsBackend

An `MsBackend` derived class must offer the following API

## Accessors

(and possible respective replacement methods)

- [X] `mz`: returns a `list` of M/Z vectors
- [X] `intensity`: returns a `list` of intensity vectors
- [x] `peaks` (new): returns a `list` of either data.frames or matrices with M/Z and intensity columns
- [x] `rtime`
- [x] `tic`
- [x] `peaksCounts`
- [X] `ionCount`
- [x] `msLevel`
- [x] `acquisitionNum`
- [x] `scanIndex`
- [x] `precursorMz` (`NA` if level 1)
- [x] `precursorCharge` (`NA` if level 1)
- [x] `precursorIntensity` (`NA` if level 1)
- [x] `precAcquisitionNum` (`NA` if level 1)
- [x] `precScanNum` (`NA` if level 1)
- [x] `collisionEnergy` (`NA` if level 1)
- [X] `fromFile`
- [X] `fileNames`
- [x] `polarity` 
- [x] `centroided` 
- [X] `isCentroided` 
- [x] `smoothed` 
- [X] `length`
- [ ] ~`spectra` (RFC 3)~
- [x] `spectraData` (replacement for `fData`) returns a `DataFrame`
- [x] `spectraVariables` (replacement for `fvarLables`) 
- [x] `selectSpectraVariables` (analogous to `MSnbase::selectFeatureData`)
- [ ] ~`spectraNames` (replacement for `featureNames`)~
- [ ] ~`metadata` returns a `list`~ (currently not considered) 
- [X] `isEmpty`
- [ ] ~`as.data.frame` and `as(, "data.frame")`~ (see `peaks`)

## Filters 

- [x] `[`
- [ ] ~`[[`~ (see RFC1 below)
- [ ] `filterFile`
- [x] `filterMsLevel`
- [x] `filterPolarity`
- [x] `filterRt`
- [x] `filterMz`
- [x] `filterAcquisitionNum`
- [x] `filterEmptySpectra`
- [x] `filterPrecursorScan`

(a tick above means that the function is documented in the [`MsBackend` man](https://github.com/lgatto/Spectra/blob/master/R/MsBackend.R#L4) page.)

See RFC2 below.

# Spectra

The following functions should be implemented at the `Spectra` level, accessing the data using the  `MsBackend`-specific accessors.

## Processing functions

- `clean`
- `removePeaks`
- `trimMz`
- `pickPeaks`
- `smooth`
- `bin`

# Misc

Here are other functions that probably also should be dealt with at the `Spectra` level.

- `quantify` (optional)
- `normalise`/`normalize` (optional)
- `compareSpectra`
- `estimateNoise`
- `removeReporters` (optional)
- `estimateResolution`

Other: chromatogram alignment, peak matching/spectra alignment, ...

## Request for comments (RFC)

1. Do we still need `[[`, and if so, what will we return? And in memory `Spectrum` object without its associated `spectraData` `DataFrame`?

2. For these filtering function, should be consider a `filter(key OP value)` `dplyr`-like syntax? Something like
```r
x %>% filter(msLevel == 2, precursorCharge > 2, precursorIntensity > median(precursorIntensity))
```

3. Do we still need `spectra` and if so, what will it return? A list of `Spectrum` objects? 

4. In the interest of consistency, I think we accessors should always return the same type of results, irrespective of the length of `Spectra`, i.e. no implicit `simplify = TRUE`.  This output would be a vector except when stated explicitly.

**Comment by jorainer** [comment]
@lgatto, are these here definitions for the `Spectra` class or the `MsBackend`? I would split the functionality between the `Spectra` and the `MsBackend` such that all preprocessing methods are defined for `Spectra`, while the `MsBackend` should ideally have only methods to provide and set the data. In other words, I would implement methods such as `normalise`, `clean` etc only for `Spectra`, while `MsBackend` (and also `Spectra`) will have methods `polarity`, `fromFile` etc.

Regarding the RFC:
1) nope, no need for that.
2) yes. That's doable - but why not `x %>% filter(mzLevel == 2 & precursorCharge > 2)` - we could even think of reusing the `AnnotationFilter` framework for that (?).
3) nope. No `spectra` method needed.
4) yes. And e.g. `mz` should always return a `list` of `numeric`, even if `length` of `Spectra` is one.

**Comment by lgatto** [comment]
Indeed, you are right with the split between Spectra and Backend. Will update when I get a chance, or feel free to update yourself.

**Comment by lgatto** [comment]
And definitely yes to reuse `AnnotationFilter`! :+1:

**Comment by lgatto** [comment]
Some further thoughts whether implementation should exist at the `Spectra` or `MsBackend` level. Ideally, we would want to have a standard implementation for a processing function in `Spectra`, that would work for all backends, but that some backends optionally provide their own optimised version.

**Comment by jorainer** [comment]
Was just wondering - we don't have a `precAcquisitionNum` method in `MSnbase`, and do also not record the acquisition number of the precursor, only the scan number (`precScanNum`). I guess we can drop that method.

**Comment by jorainer** [comment]
And the `metadata` should go to `Spectra`, as we don't have that slot/information in the backend.

**Comment by lgatto** [comment]
@jorainer - I was that many generics are defined in `Spectra`'s `AllGenerics.R` file. Are these, or some at least not already in `ProtGenerics`? Or if not, shouldn't they be added there?

**Comment by jorainer** [comment]
Nope - all the ones in `AllGenerrics.R` are defined in `MSnbase`, but not in `ProtGenerics`.

**Comment by jorainer** [comment]
And I think we might want to move them only *after* the Bioc3.9 release, otherwise we might start breaking things just before the code freeze.

**Comment by jorainer** [comment]
Regarding RFC1 (need for a `[[` method):
I think it would be nice to have that method in the backend, but to access a *spectra variable*, not a single spectrum element. Why? We need to allow the user to add arbitrary annotation columns to a `Spectra` object (which will then be *stored* in the backend). Let's assume we have a `Spectra` `sps` with 3 spectra. Adding an additional column could then be performed with:

```r
sps$spectrum_id <- c("a", "b", "c")
```

This is currently possible because I've implemented a `spectraData<-` method and 
```r
setReplaceMethod("$", "Spectra", function(x, name, value) {
    spectraData(x)[[name]] <- value
    x
})
```

Problem with this is that a call to `$<-` replaces the full `spectraData` `DataFrame` and I'm afraid that this will involve a lot of copying (which we don't want, especially if we have large experiments/`Spectra` objects).

The solution would be to have a `[[<-,MsBackend` method that would allow to replace or add a spectra variable (i.e. a column in the `spectraData` `DataFrame` e.g. for `MsBackendDataFrame`).

Any objections @lgatto ?

**Comment by jorainer** [comment]
Update: `[[` to access columns might be unintuitive: `[` allows only to select subset spectra (i.e. rows) thus it makes no sense to have `[[` access only spectra variables (columns). Better to directly implement the `$,MsBackend` and `$<-,MsBackend` to get/set a spectra variable (column) in the backend. That way `Spectra` and the new `Spectrum` would have the same logic to access spectra variables.

**Comment by jorainer** [comment]
Additional methods I would propose:
- [ ] `peaks<-` to allow replacing the peaks
- [ ] `mz<-`
- [ ] `intensity<-`
- [ ] `spectraData<-`
- [ ] `$<-`

These enable to replace/update spectra variables and/or peak data. Not all backends will support all of them.

**Comment by lgatto** [comment]
For in memory backends, the implementation of these replacement methods is straightforward. How to you see it for on disk backends that support them? Writing every time? Some lazy evaluation? Caching the results and writing on disk intermittently?

**Comment by jorainer** [comment]
That's up to the backend. So far I have played with an Hdf5 backend where I am writing each time. Note that so far I did not implement these methods for the `Spectra`, which will be the main user interface. The `Spectra` uses lazy evaluation as we can not guarantee that every backend supports write support.

So, the idea was to perform data manipulations on `Spectra` (of the peak matrix) using dedicated methods (such as `normalize`, `clean` etc) and cache these in the processing queue. To support arbitrary data manipulations I will implement a `peaksapply` method (which `FUN` will also be added to the lazy processing queue). To make changes permanent we could have a `applyProcessingQueue` method that executes all the lazy processing steps and writes the changes to the backend (hence the `peaks<-` method in the backend) - this will fail for e.g. `MsBackendMzR` because that does not support writing data.
